// Vernissage dev environment — all resources (resource-group scope).
// Invoked as a module from main.bicep.

param location string
param swaLocation string
param appServicePlanName string
param webAppName string
param staticWebAppName string
param deployIdentityName string
param logAnalyticsName string
param appInsightsName string
param sqlServerName string
param sqlDatabaseName string
param sqlAdminLogin string

@secure()
param sqlAdminPassword string

@secure()
param jwtSigningKey string

param clientIpAddress string
param httpLoggingRetentionDays int
param gitHubRepository string

// Website Contributor — lets the GitHub OIDC identity deploy to the web app and nothing else.
var websiteContributorRoleId = 'de139f84-1756-47ae-9be6-808fbbe84772'

var sqlConnectionString = 'Server=tcp:${sqlServer.properties.fullyQualifiedDomainName},1433;Initial Catalog=${sqlDatabaseName};Persist Security Info=False;User ID=${sqlAdminLogin};Password=${sqlAdminPassword};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

// --- Observability -----------------------------------------------------------

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logAnalyticsName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
    // Dev environment: cap ingestion so cost stays ~0 even if something goes chatty.
    workspaceCapping: {
      dailyQuotaGb: json('0.1')
    }
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
    IngestionMode: 'LogAnalytics'
  }
}

// --- SQL ---------------------------------------------------------------------

resource sqlServer 'Microsoft.Sql/servers@2023-08-01' = {
  name: sqlServerName
  location: location
  properties: {
    administratorLogin: sqlAdminLogin
    administratorLoginPassword: sqlAdminPassword
    version: '12.0'
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
  }
}

// 0.0.0.0-0.0.0.0 is the ARM idiom for "allow Azure services" (portal checkbox).
resource allowAzureServices 'Microsoft.Sql/servers/firewallRules@2023-08-01' = {
  parent: sqlServer
  name: 'AllowAllWindowsAzureIps'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
}

resource clientIpRule 'Microsoft.Sql/servers/firewallRules@2023-08-01' = if (clientIpAddress != '') {
  parent: sqlServer
  name: 'dev-client-ip'
  properties: {
    startIpAddress: clientIpAddress
    endIpAddress: clientIpAddress
  }
}

resource sqlDatabase 'Microsoft.Sql/servers/databases@2023-08-01' = {
  parent: sqlServer
  name: sqlDatabaseName
  location: location
  sku: {
    name: 'GP_S_Gen5'
    tier: 'GeneralPurpose'
    family: 'Gen5'
    capacity: 2
  }
  properties: {
    collation: 'SQL_Latin1_General_CP1_CI_AS'
    autoPauseDelay: 60
    minCapacity: json('0.5')
    maxSizeBytes: 34359738368
    zoneRedundant: false
    requestedBackupStorageRedundancy: 'Local'
    // Free serverless offer — can only be set at creation; without it the DB bills normally.
    useFreeLimit: true
    freeLimitExhaustionBehavior: 'AutoPause'
  }
}

// --- API App Service ---------------------------------------------------------

resource appServicePlan 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: appServicePlanName
  location: location
  kind: 'app' // Windows
  sku: {
    name: 'F1'
    tier: 'Free'
    size: 'F1'
    family: 'F'
    capacity: 0
  }
}

resource webApp 'Microsoft.Web/sites@2024-04-01' = {
  name: webAppName
  location: location
  kind: 'app'
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    clientAffinityEnabled: true
    // Regionalized unique default hostname (name-<hash>.<region>-01.azurewebsites.net),
    // matching how the original portal-created site was configured.
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    siteConfig: {
      netFrameworkVersion: 'v10.0'
      use32BitWorkerProcess: true // required on F1
      alwaysOn: false // F1 does not support Always On
      ftpsState: 'FtpsOnly'
      minTlsVersion: '1.2'
      http20Enabled: false
      appSettings: [
        {
          name: 'ConnectionStrings__DefaultConnection'
          value: sqlConnectionString
        }
        {
          name: 'Jwt__SigningKey'
          value: jwtSigningKey
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: appInsights.properties.ConnectionString
        }
        {
          name: 'WEBSITE_HTTPLOGGING_RETENTION_DAYS'
          value: string(httpLoggingRetentionDays)
        }
      ]
    }
  }
}

// Portal "Stack" display for Windows .NET sites (cosmetic; runtime is netFrameworkVersion).
resource webAppMetadata 'Microsoft.Web/sites/config@2024-04-01' = {
  parent: webApp
  name: 'metadata'
  properties: {
    CURRENT_STACK: 'dotnet'
  }
}

// --- GitHub OIDC deploy identity --------------------------------------------

resource deployIdentity 'Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30' = {
  name: deployIdentityName
  location: location
}

// The API deploy workflow's deploy job runs in GitHub environment `dev`.
resource ficEnvironmentDev 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2024-11-30' = {
  parent: deployIdentity
  name: 'github-env-dev'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:${gitHubRepository}:environment:dev'
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
}

resource ficBranchDevelop 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2024-11-30' = {
  parent: deployIdentity
  name: 'github-branch-develop'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:${gitHubRepository}:ref:refs/heads/develop'
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
  // Azure rejects concurrent federated-credential writes on one identity; serialize them.
  dependsOn: [
    ficEnvironmentDev
  ]
}

resource deploySiteRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  scope: webApp
  name: guid(webApp.id, deployIdentity.id, websiteContributorRoleId)
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', websiteContributorRoleId)
    principalId: deployIdentity.properties.principalId
    principalType: 'ServicePrincipal'
  }
}

// --- Frontend Static Web App -------------------------------------------------

// Deliberately not linked to the GitHub repo: deploys use the deployment token
// (Azure/static-web-apps-deploy@v1), which works without repository linkage.
resource staticWebApp 'Microsoft.Web/staticSites@2024-04-01' = {
  name: staticWebAppName
  location: swaLocation
  sku: {
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    stagingEnvironmentPolicy: 'Enabled'
    allowConfigFileUpdates: true
  }
}

// --- Outputs -----------------------------------------------------------------

output apiDefaultHostname string = webApp.properties.defaultHostName
output swaDefaultHostname string = staticWebApp.properties.defaultHostname
output deployIdentityClientId string = deployIdentity.properties.clientId
output sqlServerFqdn string = sqlServer.properties.fullyQualifiedDomainName
output appInsightsConnectionString string = appInsights.properties.ConnectionString
