// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vernissage.Api.Data;

#nullable disable

namespace Vernissage.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260707090328_InitialExhibitions")]
partial class InitialExhibitions
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Vernissage.Api.Models.Exhibition", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Aim")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ArtworksList")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTimeOffset>("CreatedAtUtc")
                .HasColumnType("datetimeoffset");

            b.Property<string>("Curator")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<DateOnly?>("EndDate")
                .HasColumnType("date");

            b.Property<string>("EventsDetails")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Explication")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("GalleryLocation")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("InvestigationMaterial")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("Location")
                .HasMaxLength(500)
                .HasColumnType("nvarchar(500)");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnType("nvarchar(300)");

            b.Property<string>("Notes")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("OpeningDetails")
                .HasColumnType("nvarchar(max)");

            b.Property<Guid?>("OwnerId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("PreOpeningDetails")
                .HasColumnType("nvarchar(max)");

            b.Property<string>("ReferencedLiterature")
                .HasColumnType("nvarchar(max)");

            b.Property<DateOnly?>("StartDate")
                .HasColumnType("date");

            b.Property<string>("Team")
                .HasColumnType("nvarchar(max)");

            b.Property<DateTimeOffset>("UpdatedAtUtc")
                .HasColumnType("datetimeoffset");

            b.HasKey("Id");

            b.ToTable("Exhibitions");
        });

        modelBuilder.Entity("Vernissage.Api.Models.ExhibitionMedia", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier");

            b.Property<string>("Caption")
                .HasMaxLength(1000)
                .HasColumnType("nvarchar(1000)");

            b.Property<int>("Category")
                .HasColumnType("int");

            b.Property<byte[]>("Content")
                .IsRequired()
                .HasColumnType("varbinary(max)");

            b.Property<string>("ContentType")
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnType("nvarchar(200)");

            b.Property<DateTimeOffset>("CreatedAtUtc")
                .HasColumnType("datetimeoffset");

            b.Property<Guid>("ExhibitionId")
                .HasColumnType("uniqueidentifier");

            b.Property<string>("FileName")
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnType("nvarchar(400)");

            b.Property<long>("FileSize")
                .HasColumnType("bigint");

            b.HasKey("Id");

            b.HasIndex("ExhibitionId", "Category");

            b.ToTable("ExhibitionMedia");
        });

        modelBuilder.Entity("Vernissage.Api.Models.ExhibitionMedia", b =>
        {
            b.HasOne("Vernissage.Api.Models.Exhibition", "Exhibition")
                .WithMany("Media")
                .HasForeignKey("ExhibitionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Exhibition");
        });

        modelBuilder.Entity("Vernissage.Api.Models.Exhibition", b =>
        {
            b.Navigation("Media");
        });
#pragma warning restore 612, 618
    }
}
